export { default as Home } from './Home/Home';
export { default as AboutMe } from './AboutMe/AboutMe';
export { default as Education } from './Education/Education';
export { default as Employment } from './Employment/Employment';
export { default as Achievements } from './Achievements/Achievements';
export { default as Research } from './Research/Research';
export { default as Projects } from './Projects/Projects';
export { default as Collabs } from './Collab/Collab';
export { default as Footer } from './Footer/Footer';